### ISSUE TITLE
Switch from pysvn to svn?

### ISSUE THREAD

**Issue by shippy** [sibis-platform/sibispy#9]
[PySVN](http://pysvn.tigris.org/pysvn_FAQ.html) as used by sibispy is not currently on PyPI and therefore not `pip` installable. I'd like to investigate how difficult it would be to substitute `pip install `[`svn`](https://pypi.python.org/pypi/svn) (which, confusingly, is on Github as [PySVN](https://github.com/dsoprea/PySvn), too).

**Comment by shippy** [comment]
Alternative: take the `import pysvn` statement and stick it inside the only method that really requires it, which is `Session.__connect_svn_laptop__`. Then, handle the `ImportError` as needed.

(The primary reason for the suggested switch is that non-pippable packages make for a harder-to-set-up environment, even if you only want to use sibispy for Redcap API connections. This would address that underlying reason instead of changing up the stack.)

**Comment by shippy** [comment]
cc: @jimklo

**Comment by jimklo** [comment]
It also makes 2to3 a bit easier. Tigris pysvn because it’s native, is locked to specific Python version, svn version, and libc versions - basically you cave to just compile it for any platform that doesn’t have the right combination of matching dependencies.  The ‘svn’ module just needs the svn cli to do its bidding - it doesn’t try to get around the shell by using libsvn.

**Comment by shippy** [comment]
The good news is that `pysvn` isn't widely used around our codebase.

be48f27744f43534da94462f8cbd40aed9699dc0 added most of the functionality and exposed `Session.run_svn`. [harvester](https://github.com/sibis-platform/ncanda-data-integration/blob/b5c9c00370a36739222a773b4dcb44447ecc34a9/scripts/import/laptops/harvester#L332) uses `pysvn` to define a callback function to be included in the `Session.run_svn` call, but - as far as I can tell - nowhere else.

**Comment by shippy** [comment]
Closed in #28.
